### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by andrewspiers** [rembish/fit#2]
In [1]: from fit import FitFile                                                                                                                                                                             
Traceback (most recent call last):

  File "/mnt/c/Users/andre/Documents/FIT experiment/venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-eb542d3867c8>", line 1, in <module>
    from fit import FitFile

  File "/mnt/c/Users/andre/Documents/FIT experiment/venv/lib/python3.6/site-packages/fit/__init__.py", line 53
    raise exc_type, exc_val, exc_tb
                  ^
SyntaxError: invalid syntax

**Comment by rembish** [comment]
Fixed in v0.5.1. The `raise exc_type, exc_val, exc_tb` Python 2 syntax and all other Python 2 compatibility shims have been removed — the library now requires Python ≥ 3.9. Thanks for the report!
